image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

after_script:
- docker images

build PHP:
  stage: build
  script:
  - docker build --build-arg --pull --tag $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE:latest

build PHP7.0:
  stage: build
  script:
  - docker build --build-arg VERSION=7.0 --pull --tag $CI_REGISTRY_IMAGE:7.0 .
  - docker push $CI_REGISTRY_IMAGE:7.0

build PHP7.1:
  stage: build
  script:
  - docker build --build-arg VERSION=7.1 --pull --tag $CI_REGISTRY_IMAGE:7.1 .
  - docker push $CI_REGISTRY_IMAGE:7.1

